---
development:
  cloud_name: dhdl31ov5
  api_key: '744871436812119'
  api_secret: NNXRU7AMwaq2mwGaHYuoRh-alMM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dhdl31ov5
  api_key: '744871436812119'
  api_secret: NNXRU7AMwaq2mwGaHYuoRh-alMM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dhdl31ov5
  api_key: '744871436812119'
  api_secret: NNXRU7AMwaq2mwGaHYuoRh-alMM
  enhance_image_tag: true
  static_image_support: false
