---
development:
  cloud_name: drrla92sh
  api_key: '679824314598265'
  api_secret: MqWNdYS2GmsGOtlnzn_ntY3kjFY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: drrla92sh
  api_key: '679824314598265'
  api_secret: MqWNdYS2GmsGOtlnzn_ntY3kjFY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drrla92sh
  api_key: '679824314598265'
  api_secret: MqWNdYS2GmsGOtlnzn_ntY3kjFY
  enhance_image_tag: true
  static_image_support: false
