test: &default

  # Credentials for REST APIs
  client_id: Ae-fw4632RySsb8cADQKW9dWjOFCbuHdEecSBh2MIYPZK9Lb0or7TffwNt84tj5ZeMDizTUEgRv_1eBz
  client_secret: EKU0rWK1TUmZzwokbgk1C1KIecOqRJziR6xcw1II41yEp4630wl7e7TR_kReO8ah6I3D7AsAqjs8tBHX

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: social-booker
  username: contact-facilitator_api1.socialbooker.io
  password: S2KRTMNYPZBCWHR5
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AST4oDLwtjHZA5yMnzddieQ8if6s
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: contact-facilitator@socialbooker.io

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
